# Generated by Django 3.2.3 on 2021-10-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_login_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
