# Generated by Django 3.2.5 on 2021-08-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deladmin', '0002_adminlogin_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='adminLogin',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
