# Generated by Django 3.2.3 on 2021-10-12 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deladmin', '0004_adminlogin_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deladmin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deladmin.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deladmin.product')),
            ],
        ),
    ]
