# Generated by Django 3.2.3 on 2021-10-13 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deladmin', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
