# Generated by Django 3.2.3 on 2021-10-20 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deladmin', '0009_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='image',
            name='category',
        ),
    ]
